/*recuperar o nome e endereço dos funcionarios que trabalham para o departamento de pesquisa*/
SELECT TB_FUNCIONARIO.PRIMEIRO_NOME, TB_FUNCIONARIO.NOME_MEIO, TB_FUNCIONARIO.ULTIMO_NOME, TB_FUNCIONARIO.ENDERECO 
FROM TB_FUNCIONARIO
INNER JOIN TB_DEPARTAMENTO
ON TB_FUNCIONARIO.NUMERO_DEPARTAMENTO = TB_DEPARTAMENTO.NUMERO_DEPARTAMENTO
WHERE TB_DEPARTAMENTO.NOME_DEPARTAMENTO = 'Pesquisa';