/*descobrir os nomes dos funcionarios que trabalham em TODOS os projetos controlados pelo departamento 5*/
SELECT TB_FUNCIONARIO.PRIMEIRO_NOME, TB_FUNCIONARIO.NOME_MEIO, TB_FUNCIONARIO.ULTIMO_NOME
FROM TB_PROJETO
INNER JOIN TB_TRABALHA_EM
ON TB_PROJETO.NUMERO_PROJETO = TB_TRABALHA_EM.NUMERO_PROJETO
INNER JOIN TB_FUNCIONARIO
ON TB_FUNCIONARIO.CPF = TB_TRABALHA_EM.CPF_FUNCIONARIO
WHERE TB_PROJETO.NUMERO_DEPARTAMENTO = 5;

/*utilizando o comando COUNT(*)*/
SELECT COUNT(*) FROM TB_PROJETO WHERE TB_PROJETO.NUMERO_DEPARTAMENTO = 5;

/*aplicando no cabeçalho - precisa usar o comando GROUP BY*/
SELECT TB_FUNCIONARIO.PRIMEIRO_NOME, TB_FUNCIONARIO.NOME_MEIO, TB_FUNCIONARIO.ULTIMO_NOME
FROM TB_PROJETO
INNER JOIN TB_TRABALHA_EM
ON TB_PROJETO.NUMERO_PROJETO = TB_TRABALHA_EM.NUMERO_PROJETO
INNER JOIN TB_FUNCIONARIO
ON TB_FUNCIONARIO.CPF = TB_TRABALHA_EM.CPF_FUNCIONARIO
WHERE TB_PROJETO.NUMERO_DEPARTAMENTO = 5
GROUP BY TB_FUNCIONARIO.PRIMEIRO_NOME, TB_FUNCIONARIO.NOME_MEIO, TB_FUNCIONARIO.ULTIMO_NOME

/*o fernando wong é o unico que trabalhou em todos os projetos do departamento 5 - fazer com que a consulta seja dinamica*/
/*nao podemos usar o comando AND pq fica fora do WHERE, mas tem que ser depois do GROUP BY - então usamos o HAVING*/
HAVING COUNT(*) = (SELECT COUNT(*) FROM TB_PROJETO WHERE TB_PROJETO.NUMERO_DEPARTAMENTO = 5);